!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        01zF6E1Z-User Interface:
          path: dataset/01zF6E1Z-User Interface
          prefix: ncino
          standardFeature: false
          versions:
            05 April 2021:
              modifiedDate: '2021-09-01 18:29:30'
        01zF6E1Z-Questionaire:
          path: dataset/01zF6E1Z-Questionaire
          prefix: ncino
          standardFeature: false
          versions:
            Spring 2020 v3:
              modifiedDate: '2021-09-02 14:12:49'
        01zF6E1Z-Connection Roles:
          path: dataset/01zF6E1Z-Connection Roles
          prefix: ncino
          standardFeature: false
          versions:
            Spring 2020 V2:
              modifiedDate: '2021-09-02 14:18:13'
        01zF6E1Z-Document Manager:
          path: dataset/01zF6E1Z-Document Manager
          prefix: ncino
          standardFeature: false
          versions:
            Spring 2020 V1:
              modifiedDate: '2021-09-02 14:25:30'
        10g3wC1H-Risk Grade Templates:
          path: dataset/10g3wC1H-Risk Grade Templates
          prefix: ncino
          standardFeature: false
          versions:
            Fall 2019:
              modifiedDate: '2021-09-02 14:42:27'
